### ISSUE TITLE
Bug in Scenic example

### ISSUE THREAD

**Issue by abol-karimi** [BerkeleyLearnVerify/VerifAI#14]
When I run `examples/carla/scenic/scenic_sampler.py` I get 
`ModuleNotFoundError: No module named 'scenic.simulators.carla.road_model'`

The file `examples/carla/scenic/adjacentOpposingPair.sc` uses `from scenic.simulators.carla.road_model import *` but it seems that `road_model` does not exist in Scenic anymore.

**Comment by WhoAmI-kai** [comment]
I also encountered the same problem. Have you solved it？

**Comment by findaheng** [comment]
The `road_model` was changed to just `model`. There is an [updated example of this scenario](https://github.com/BerkeleyLearnVerify/Scenic/blob/master/examples/carla/adjacentOpposingPair.scenic) in the main Scenic repository. I've also made a [pull request](https://github.com/BerkeleyLearnVerify/VerifAI/pull/28) to make this fix here as well.
