### ISSUE TITLE
Bug in Carla example

### ISSUE THREAD

**Issue by abol-karimi** [BerkeleyLearnVerify/VerifAI#15]
Running `examples/carla/pid_control/pid_control_simulator.py` throws `add_vehicle() got an unexpected keyword argument 'blueprint'`.

**Comment by siruissss** [comment]
you need to modify argument 'blueprint',
self.world.add_vehicle(PIDAgent, control_params=opt_dict,
                               blueprint_filter=blueprint.id, spawn=spawn,
                               physics=physics, has_collision_sensor=True,
                               has_lane_sensor=True, ego=True)

**Comment by dfremont** [comment]
I'm guessing this was a CARLA API change, but in any case, the new CARLA examples go through Scenic and don't have this problem. Please feel free to file a new issue if you can't get those to run.
