### ISSUE TITLE
This is not compatible with python 3.9.2?

### ISSUE THREAD

**Issue by parsecby3-26** [BerkeleyLearnVerify/VerifAI#16]
I downloaded the latest version since the version i had(3.7.3) did not work well when i ran poetry install. It threw this error at me:

poetry install
Installing dependencies from lock file

Package operations: 30 installs, 0 updates, 0 removals

  • Installing scipy (1.5.3)

  EnvCommandError

  Command C:\Users\HP\Anaconda3\envs\py39\Scripts\pip.exe install --no-deps file:///C:/Users/HP/AppData/Local/pypoetry/Cache/artifacts/1e/6f/da/dab4f4dc31b4da29c922bdb9bdbda8711018deccaa4297665d1fbd4fc7/scipy-1.5.3.tar.gz errored with the following return code 1, and output:
  Processing c:\users\hp\appdata\local\pypoetry\cache\artifacts\1e\6f\da\dab4f4dc31b4da29c922bdb9bdbda8711018deccaa4297665d1fbd4fc7\scipy-1.5.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\HP\Anaconda3\envs\py39\python.exe' 'C:\Users\HP\Anaconda3\envs\py39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmpav1eh1tj'
           cwd: C:\Users\HP\AppData\Local\Temp\pip-req-build-m_nrqfmo
      Complete output (219 lines):
      setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-oskiom27'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      Running from SciPy source directory.
      lapack_opt_info:
      lapack_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['C:\\Users\\HP\\Anaconda3\\envs\\py39\\lib', 'C:\\', 'C:\\Users\\HP\\Anaconda3\\envs\\py39\\libs', 'C:\\Users\\HP\\Anaconda3\\Library\\lib']
        NOT AVAILABLE

      openblas_lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['C:\\Users\\HP\\Anaconda3\\envs\\py39\\lib', 'C:\\', 'C:\\Users\\HP\\Anaconda3\\envs\\py39\\libs', 'C:\\Users\\HP\\Anaconda3\\Library\\lib']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      openblas_clapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas,lapack not found in ['C:\\Users\\HP\\Anaconda3\\envs\\py39\\lib', 'C:\\', 'C:\\Users\\HP\\Anaconda3\\envs\\py39\\libs', 'C:\\Users\\HP\\Anaconda3\\Library\\lib']
        NOT AVAILABLE

      flame_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries flame not found in ['C:\\Users\\HP\\Anaconda3\\envs\\py39\\lib', 'C:\\', 'C:\\Users\\HP\\Anaconda3\\envs\\py39\\libs', 'C:\\Users\\HP\\Anaconda3\\Library\\lib']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\Library\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\Users\HP\Anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\Library\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\Users\HP\Anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\Library\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\HP\Anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\Users\HP\Anaconda3\envs\py39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\Users\HP\Anaconda3\envs\py39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\Users\HP\Anaconda3\Library\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\Users\HP\Anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack not found in ['C:\\Users\\HP\\Anaconda3\\envs\\py39\\lib', 'C:\\', 'C:\\Users\\HP\\Anaconda3\\envs\\py39\\libs', 'C:\\Users\\HP\\Anaconda3\\Library\\lib']
        NOT AVAILABLE

      C:\Users\HP\AppData\Local\Temp\pip-build-env-cpu8laxv\overlay\Lib\site-packages\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\HP\AppData\Local\Temp\pip-build-env-cpu8laxv\overlay\Lib\site-packages\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
        NOT AVAILABLE

      Traceback (most recent call last):
        File "C:\Users\HP\Anaconda3\envs\py39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
          main()
        File "C:\Users\HP\Anaconda3\envs\py39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\HP\Anaconda3\envs\py39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-cpu8laxv\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-cpu8laxv\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-cpu8laxv\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 583, in <module>
          setup_package()
        File "setup.py", line 579, in setup_package
          setup(**metadata)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-cpu8laxv\overlay\Lib\site-packages\numpy\distutils\core.py", line 137, in setup
          config = configuration()
        File "setup.py", line 477, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
      ----------------------------------------
  WARNING: Discarding file:///C:/Users/HP/AppData/Local/pypoetry/Cache/artifacts/1e/6f/da/dab4f4dc31b4da29c922bdb9bdbda8711018deccaa4297665d1fbd4fc7/scipy-1.5.3.tar.gz. Command errored out with exit status 1: 'C:\Users\HP\Anaconda3\envs\py39\python.exe' 'C:\Users\HP\Anaconda3\envs\py39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmpav1eh1tj' Check the logs for full command output.
  ERROR: Command errored out with exit status 1: 'C:\Users\HP\Anaconda3\envs\py39\python.exe' 'C:\Users\HP\Anaconda3\envs\py39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmpav1eh1tj' Check the logs for full command output.

  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):

**Comment by dfremont** [comment]
It looks like your problem was that Scipy didn't have a wheel available for your system, so it had to be compiled from source, which then failed because you didn't have LAPACK/BLAS installed. This isn't an issue with VerifAI at all -- hopefully you're now able to install Scipy! In any case VerifAI supports Python 3.8-3.10.
