### ISSUE TITLE
Bug in Basic Usage Method 1

### ISSUE THREAD

**Issue by StevenCHowell** [BerkeleyLearnVerify/VerifAI#33]
The [Method 1 example of the Basic Usage Documentation](https://github.com/BerkeleyLearnVerify/VerifAI/blob/master/docs/basic_usage.rst#method-1-using-reffeature-apis) creates a dictionary from three instances of the [`verifai.features.features.Struct`](https://github.com/BerkeleyLearnVerify/VerifAI/blob/master/src/verifai/features/features.py#L716) class, then uses that dictionary to instantiate a [`verifai.samplers.feature_sampler.LateFeatureSampler`](https://github.com/BerkeleyLearnVerify/VerifAI/blob/master/src/verifai/samplers/feature_sampler.py#L185) object by calling the [`randomSampleFor`](https://github.com/BerkeleyLearnVerify/VerifAI/blob/master/src/verifai/samplers/feature_sampler.py) method of the [`verifai.samplers.feature_sampler.FeatureSampler`](https://github.com/BerkeleyLearnVerify/VerifAI/blob/master/src/verifai/samplers/feature_sampler.py#L24) class.  Instantiating the `LateFeatureSampler` method results in an error when [trying to access the `domains` attribute of the input dictionary](https://github.com/BerkeleyLearnVerify/VerifAI/blob/master/src/verifai/samplers/feature_sampler.py#L196).  

I cannot reconcile what this `domains` attribute is meant to be, as the three dictionary keys in the example are `'control_params'`, `'env_params'`, and `'cones_config'`.  I wondered if it meant to be accessing the `'domain'` key, but that is not one of the options.

How is this example meant to function?

**Comment by abadithela** [comment]
Same issue. Have you found a solution to this yet?

**Comment by dfremont** [comment]
Thanks for catching this, and apologies for the very slow reply! I'm not sure how that example got messed up, but the code was wrong: the Structs need to be used to define Features, then those need to be put into a FeatureSpace, not a plain dict. I've updated the documentation.
